services:
  mongo:
    image: mongo:latest
    container_name: go-mongodb-rest
    env_file:
        - ./.env
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    stdin_open: true
    tty: true
