services:
  db:
    image: postgres:alpine3.20
    container_name: go-postgres
    env_file: 
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      retries: 5

